sonar.projectKey=johnfewell_anytime_podcast_player
sonar.organization=johnfewell

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=anytime_podcast_player
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
